apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
    name: k8s-multi-com-tls
spec:
    secretName: k8s-multi-com
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: justalittledomain.com
    dnsNames:
        - justalittledomain.com
        - www.justalittledomain.com
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - justalittledomain.com
                - www.justalittledomain.com
        
