apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ingress-service
    annotations:
        kubernetes.io/ingress.class: nginx # tell k8s we want to create ingress controller base on the nginx project
        nginx.ingress.kubernetes.io/rewrite-target: /$1 # how the copy of nginx behalf, so that '/' will be used instead of '/api' in server side
        certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
        nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
    tls:
        - hosts:
            - justalittledomain.com
            - www.justalittledomain.com
          secretName: k8s-multi-com
    rules:
        - host: justalittledomain.com
          http:
            paths:
                - path: /?(.*)
                  backend:
                      serviceName: client-cluster-ip-service
                      servicePort: 3000
                - path: /api/?(.*) 
                  backend:
                      serviceName: server-cluster-ip-service
                      servicePort: 5000
        - host: www.justalittledomain.com
          http:
            paths:
                - path: /?(.*)
                  backend:
                      serviceName: client-cluster-ip-service
                      servicePort: 3000
                - path: /api/?(.*) 
                  backend:
                      serviceName: server-cluster-ip-service
                      servicePort: 5000
